POST http://localhost:3001/api/patients
Content-Type: application/json

    {
       
        "dateOfBirth": "1969-11-30",
        "ssn": "300174-77B",
        "gender": "male",
        "occupation": "Cop2"
    }